[package]
name = "tosspay"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
